# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resumeMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os, pyperclip
from os.path import expanduser
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QWidget, QPushButton, QFileDialog, QApplication, QDialog)
backend = __import__('resumeBackend')
home = expanduser("~")

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(422, 193)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(422, 193))
        MainWindow.setMaximumSize(QtCore.QSize(422, 193))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Resume = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Resume.sizePolicy().hasHeightForWidth())
        self.Resume.setSizePolicy(sizePolicy)
        self.Resume.setTextFormat(QtCore.Qt.RichText)
        self.Resume.setScaledContents(False)
        self.Resume.setAlignment(QtCore.Qt.AlignCenter)
        self.Resume.setObjectName("Resume")
        self.verticalLayout.addWidget(self.Resume)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Add = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Add.sizePolicy().hasHeightForWidth())
        self.Add.setSizePolicy(sizePolicy)
        self.Add.setMinimumSize(QtCore.QSize(130, 52))
        self.Add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Add.setObjectName("Add")
        self.Add.clicked.connect(self.ShowAddDialog) #link add button to addResume
        self.horizontalLayout_2.addWidget(self.Add)
        self.Remove = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Remove.sizePolicy().hasHeightForWidth())
        self.Remove.setSizePolicy(sizePolicy)
        self.Remove.setMinimumSize(QtCore.QSize(130, 52))
        self.Remove.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Remove.setObjectName("Remove")
        self.Remove.clicked.connect(self.ShowDelDialog) #link remove button to delResume
        self.horizontalLayout_2.addWidget(self.Remove)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.Description = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Description.sizePolicy().hasHeightForWidth())
        self.Description.setSizePolicy(sizePolicy)
        self.Description.setAlignment(QtCore.Qt.AlignCenter)
        self.Description.setObjectName("Description")
        self.verticalLayout.addWidget(self.Description)
        self.PasteJobDescription = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PasteJobDescription.sizePolicy().hasHeightForWidth())
        self.PasteJobDescription.setSizePolicy(sizePolicy)
        self.PasteJobDescription.setMinimumSize(QtCore.QSize(398, 58))
        self.PasteJobDescription.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PasteJobDescription.setObjectName("PasteJobDescription")
        self.PasteJobDescription.clicked.connect(self.pasteDescription)
        self.verticalLayout.addWidget(self.PasteJobDescription)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Resume Selector"))
        self.Resume.setText(_translate("MainWindow", "Resume"))
        self.Add.setText(_translate("MainWindow", "Add"))
        self.Remove.setText(_translate("MainWindow", "Remove"))
        self.Description.setText(_translate("MainWindow", "Description"))
        self.PasteJobDescription.setText(_translate("MainWindow", "Paste Job Description"))

    def ShowAddDialog(self):
        widget = QWidget()
        dialog = QFileDialog()
        dialog.setDirectory(QtCore.QDir(home))
        path, ok = dialog.getOpenFileName(widget, 'Select a Resume', '','PDF Files (*.pdf)')
        if ok:
            if not backend.addResume(path): #if duplicate name exists, prompt replace dialog
                self.ShowRepDialog(path)
    
    def ShowRepDialog(self, path):
        name = os.path.basename(path)
        dlg = repDialog2(name)
        if dlg.exec_():
            backend.replaceResume(path, path)

    def ShowDelDialog(self):
        #change directory to the directory that this script is located in 
        abspath = os.path.abspath(__file__)
        respath = os.path.dirname(abspath) + '/resumePDFs'
        widget = QWidget()
        dialog = QFileDialog()
        dialog.setDirectory(QtCore.QDir(respath))
        path, ok = dialog.getOpenFileName(widget, 'Select a Resume to Delete', '', 'PDF Files (*.pdf)')
        if ok:
            os.chdir(os.path.dirname(abspath))
            backend.delResume(path)
    
    def pasteDescription(self):
        text = pyperclip.paste() #get job description text
        print(backend.findBestResume(text))


class dispDialog(QDialog):
    def __init__(self, filename):
        super(dispDialog, self).__init__()
        x = 400
        y = 115
        self.resize(x, y)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(x, y))
        self.setMaximumHeight(y)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHorizontalPolicy(QtWidgets.QSizePolicy.MinimumExpanding) # allow label to expand to full dialog width
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumWidth(306)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        #add connection to push button and push button
        
class repDialog2(QDialog):
    def __init__(self, filename):
        super(repDialog2, self).__init__()
        x = 400
        y = 115
        self.resize(x, y)
        self.setWindowTitle("Overwrite Resume")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(x, y))
        self.setMaximumHeight(y)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHorizontalPolicy(QtWidgets.QSizePolicy.MinimumExpanding) # allow label to expand to full dialog width
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumWidth(306)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(filename)
        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(self.reject)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, filename):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("replaceDialog", "Overwrite Resume"))
        self.label.setText(_translate("replaceDialog", "A resume with the name  '" + filename + "' already exists. Would you like to replace it?"))




'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.ShowRepDialog()
    sys.exit(app.exec_())
'''
